// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj3O7TmFskSzGXD40kIiBmxbMYB399do4',
    appId: '1:898207725876:web:a84fd634b7c0fd07284d61',
    messagingSenderId: '898207725876',
    projectId: 'uperitivo-b5e06',
    authDomain: 'uperitivo-b5e06.firebaseapp.com',
    storageBucket: 'uperitivo-b5e06.appspot.com',
    measurementId: 'G-NKK53SV7G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_wU_sN1utT7fn3ZcC43xXjHDQLXchsv4',
    appId: '1:898207725876:android:22e791ae3270dbee284d61',
    messagingSenderId: '898207725876',
    projectId: 'uperitivo-b5e06',
    storageBucket: 'uperitivo-b5e06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSyf9gvOdD3lfMptgttaeUMlGoUK1ETO4',
    appId: '1:898207725876:ios:1d2f648440cb0234284d61',
    messagingSenderId: '898207725876',
    projectId: 'uperitivo-b5e06',
    storageBucket: 'uperitivo-b5e06.appspot.com',
    iosBundleId: 'com.uper.itivo.uperitivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSyf9gvOdD3lfMptgttaeUMlGoUK1ETO4',
    appId: '1:898207725876:ios:60f37ccf05dd4027284d61',
    messagingSenderId: '898207725876',
    projectId: 'uperitivo-b5e06',
    storageBucket: 'uperitivo-b5e06.appspot.com',
    iosBundleId: 'com.uper.itivo.uperitivo.RunnerTests',
  );
}
